name: Docker CI Pipeline

on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }} .

      # 👇 Start Redis container (fixes your 500 error)
      - name: Create network
        run: docker network create test-net

      - name: Run Redis
        run: docker run -d --name redis --network test-net redis:7

      - name: Test app
        run: |
          docker run -d --network test-net -p 5000:5000 \
          -e REDIS_HOST=redis \
          ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}
          sleep 5
          curl --fail http://localhost:5000
      # 👇 Push only if test passes
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}